### ISSUE TITLE
Would be possible to set up a demo?

### ISSUE THREAD

**Issue by luminarious** [antfu/markdown-it-mdc#5]
It's possible I am misunderstanding something on a larger scale, but after trying several times I still haven't managed to make this work in Nuxt. Or anywhere else for that matter.

Would it be possible to set up a minimal demo to show how this is intended to be used, please?

**Comment by nobkd** [comment]
First, you could try using [`Nuxt MDC`](https://github.com/nuxt-modules/mdc) ([see docs](https://github.com/nuxt-modules/mdc/blob/main/docs/content/0.index.md)) with `Nuxt`.
Nuxt MDC uses [`remark-mdc`](https://github.com/nuxtlabs/remark-mdc) internally and is integrated in the `Nuxt` ecosystem.
(Or maybe [Nuxt Content](https://github.com/nuxt/content) fits your use case? (Also uses `Nuxt MDC`))

And otherwise, not using `Nuxt`, the [usage example](https://github.com/antfu/markdown-it-mdc?tab=readme-ov-file#usage) works almost fine for me. (I'll check if the inline component problem is just for me...)

So far, I haven't tried using `MarkdownIt` and `MarkdownIt MDC` with `Nuxt`, so I can't help out there.

**Comment by luminarious** [comment]
Thank you for being patient with me 😅

I finally realized that there are two separate steps. This plugin gives the syntax for mdc-style components in Markdown, but they will not render until I compile the markdown strings to Vue components. I'll research how to do that.

Because this is for a project that already uses Markdown-it, extending Nuxt MDC would be a much bigger pain in the ass.

**Comment by Sandros94** [comment]
@luminarious sorry to ping, but I'm looking to understand the same thing and wanted to know if you found anything.

I'm trying create a small module based on markdown-it since I only fetch data from other sources and don't need most of the functionalities from nuxt/content (not to mention that there are a couple of open issue about nuxt/content not being able to render fetched content)
